version: "2"

run:
  timeout: 1m

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false

  funlen:
    lines: 50
    statements: 40

  govet:
    enable-all: true
    disable:
      - fieldalignment

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/kinbiko/bugsnag

  gocyclo:
    min-complexity: 10

  gocognit:
    min-complexity: 11

  dupl:
    threshold: 100

  goconst:
    min-len: 10
    min-occurrences: 3

  misspell:
    locale: US

  lll:
    line-length: 165
    tab-width: 4

  unparam:
    check-exported: true

  nakedret:
    max-func-lines: 0

  prealloc:
    simple: true
    range-loops: true
    for-loops: false

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    settings:
      captLocal:
        paramsOnly: true
      rangeValCopy:
        sizeThreshold: 64

  godox:
    keywords:
      - TODO
      - FIXME

  dogsled:
    max-blank-identifiers: 2

  whitespace:
    multi-if: false
    multi-func: false

linters:
  disable:
    - wsl
    - godot
    - nlreturn
    - depguard
    - varnamelen
  settings:
    staticcheck:
      checks:
        - "all"
        - "-QF1008" # Don't suggest removing embedded field from selector
  presets:
    - bugs
    - complexity
    - format
    - performance
    - style
    - unused

formatters:
  enable:
    - gofmt
    - goimports

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - cyclop
        - dupl
        - errcheck
        - errchkjson
        - forbidigo
        - funlen
        - gocognit
        - gocyclo
        - lll
        - stylecheck
        - testpackage
        - varnamelen
        - maintidx
    - path: \.go
      linters:
        - err113

  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
