version: "2"

run:
  timeout: 1m

linters:
  default: all
  disable:
    - depguard
    - godot
    - nlreturn
    - varnamelen
    - wsl
    - gci
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
    funlen:
      lines: 50
      statements: 40
    govet:
      enable-all: true
      disable:
        - fieldalignment
    revive:
      confidence: 0.8
    gocyclo:
      min-complexity: 10
    gocognit:
      min-complexity: 11
    dupl:
      threshold: 100
    goconst:
      min-len: 10
      min-occurrences: 3
    misspell:
      locale: US
    lll:
      line-length: 165
      tab-width: 4
    nakedret:
      max-func-lines: 0
    dogsled:
      max-blank-identifiers: 2
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
    goimports:
      local-prefixes:
        - github.com/kinbiko/bugsnag
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - cyclop
          - dupl
          - errcheck
          - errchkjson
          - forbidigo
          - funlen
          - gocognit
          - gocyclo
          - mnd
          - lll
          - testpackage
          - maintidx
      - path: \.go
        linters:
          - err113

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
